/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActionType = { 'deposit' : null } |
  { 'orderPlacement' : null } |
  { 'withdrawal' : null } |
  { 'orderCompletion' : null } |
  { 'disputeRaised' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AuditTrail { 'actionType' : ActionType, 'timestamp' : bigint }
export type DisputeType = { 'buyerDispute' : null } |
  { 'sellerDispute' : null };
export interface FullProfile {
  'username' : string,
  'email' : string,
  'kycInfo' : KycInfo,
}
export interface KycInfo { 'verified' : boolean, 'kycLevel' : number }
export interface PaymentDetails {
  'bankAccountNumber' : string,
  'ifscCode' : string,
  'upiId' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'escrowBalance' : number,
  'profitWallet' : number,
  'userBalance' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminSetKycVerified' : ActorMethod<[Principal, boolean], undefined>,
  'approveWithdrawal' : ActorMethod<[Principal, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkApprovalStatus' : ActorMethod<[], boolean>,
  'checkKycStatus' : ActorMethod<[], number>,
  'confirmInrPayment' : ActorMethod<[bigint, Principal], undefined>,
  'createSellOrder' : ActorMethod<[number, number, PaymentDetails], bigint>,
  'deposit' : ActorMethod<[number], undefined>,
  'exportCsv' : ActorMethod<[], string>,
  'freezeOrder' : ActorMethod<[bigint], undefined>,
  'freezeWallet' : ActorMethod<[Principal], undefined>,
  'getAuditTrails' : ActorMethod<[Principal], Array<AuditTrail>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[Principal], FullProfile>,
  'getProfitDashboard' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[Principal], Wallet>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'issueRefund' : ActorMethod<[bigint], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'manualReleaseUsdt' : ActorMethod<[Principal, number], undefined>,
  'raiseDispute' : ActorMethod<[bigint, DisputeType], undefined>,
  'recordAuditTrail' : ActorMethod<[ActionType, bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPlatformRate' : ActorMethod<[number], undefined>,
  'toggleWithdrawalLock' : ActorMethod<[boolean], undefined>,
  'updateKyc' : ActorMethod<[], undefined>,
  'withdraw' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];