/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentDetails = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'ifscCode' : IDL.Text,
  'upiId' : IDL.Text,
});
export const ActionType = IDL.Variant({
  'deposit' : IDL.Null,
  'orderPlacement' : IDL.Null,
  'withdrawal' : IDL.Null,
  'orderCompletion' : IDL.Null,
  'disputeRaised' : IDL.Null,
});
export const AuditTrail = IDL.Record({
  'actionType' : ActionType,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const KycInfo = IDL.Record({
  'verified' : IDL.Bool,
  'kycLevel' : IDL.Nat8,
});
export const FullProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'kycInfo' : KycInfo,
});
export const Wallet = IDL.Record({
  'escrowBalance' : IDL.Float64,
  'profitWallet' : IDL.Float64,
  'userBalance' : IDL.Float64,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const DisputeType = IDL.Variant({
  'buyerDispute' : IDL.Null,
  'sellerDispute' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminSetKycVerified' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkApprovalStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'checkKycStatus' : IDL.Func([], [IDL.Nat8], ['query']),
  'confirmInrPayment' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createSellOrder' : IDL.Func(
      [IDL.Float64, IDL.Float64, PaymentDetails],
      [IDL.Nat],
      [],
    ),
  'deposit' : IDL.Func([IDL.Float64], [], []),
  'exportCsv' : IDL.Func([], [IDL.Text], ['query']),
  'freezeOrder' : IDL.Func([IDL.Nat], [], []),
  'freezeWallet' : IDL.Func([IDL.Principal], [], []),
  'getAuditTrails' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuditTrail)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [FullProfile], ['query']),
  'getProfitDashboard' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([IDL.Principal], [Wallet], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'issueRefund' : IDL.Func([IDL.Nat], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'manualReleaseUsdt' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'raiseDispute' : IDL.Func([IDL.Nat, DisputeType], [], []),
  'recordAuditTrail' : IDL.Func([ActionType, IDL.Int], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setPlatformRate' : IDL.Func([IDL.Float64], [], []),
  'toggleWithdrawalLock' : IDL.Func([IDL.Bool], [], []),
  'updateKyc' : IDL.Func([], [], []),
  'withdraw' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentDetails = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'ifscCode' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const ActionType = IDL.Variant({
    'deposit' : IDL.Null,
    'orderPlacement' : IDL.Null,
    'withdrawal' : IDL.Null,
    'orderCompletion' : IDL.Null,
    'disputeRaised' : IDL.Null,
  });
  const AuditTrail = IDL.Record({
    'actionType' : ActionType,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const KycInfo = IDL.Record({ 'verified' : IDL.Bool, 'kycLevel' : IDL.Nat8 });
  const FullProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'kycInfo' : KycInfo,
  });
  const Wallet = IDL.Record({
    'escrowBalance' : IDL.Float64,
    'profitWallet' : IDL.Float64,
    'userBalance' : IDL.Float64,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const DisputeType = IDL.Variant({
    'buyerDispute' : IDL.Null,
    'sellerDispute' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminSetKycVerified' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkApprovalStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'checkKycStatus' : IDL.Func([], [IDL.Nat8], ['query']),
    'confirmInrPayment' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createSellOrder' : IDL.Func(
        [IDL.Float64, IDL.Float64, PaymentDetails],
        [IDL.Nat],
        [],
      ),
    'deposit' : IDL.Func([IDL.Float64], [], []),
    'exportCsv' : IDL.Func([], [IDL.Text], ['query']),
    'freezeOrder' : IDL.Func([IDL.Nat], [], []),
    'freezeWallet' : IDL.Func([IDL.Principal], [], []),
    'getAuditTrails' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuditTrail)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [FullProfile], ['query']),
    'getProfitDashboard' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([IDL.Principal], [Wallet], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'issueRefund' : IDL.Func([IDL.Nat], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'manualReleaseUsdt' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'raiseDispute' : IDL.Func([IDL.Nat, DisputeType], [], []),
    'recordAuditTrail' : IDL.Func([ActionType, IDL.Int], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setPlatformRate' : IDL.Func([IDL.Float64], [], []),
    'toggleWithdrawalLock' : IDL.Func([IDL.Bool], [], []),
    'updateKyc' : IDL.Func([], [], []),
    'withdraw' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };